// Fill out your copyright notice in the Description page of Project Settings.

// #include "BattleTank.h" // autogenerated in Ben's lecture version
#include "TankBarrel.h"



// elevate gun barrel
void UTankBarrel::Elevate(float DegreesPerSecond)
{

}